when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
errors_404:
    path: 404.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: errors/404.html.twig
    options:
        stenope:
            sitemap: false
