# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route

# @see https://github.com/symfony/symfony/issues/32996#issuecomment-525416971

homepage:
    path: /{_locale}{_</(?!/)>}
    controller: App\Controller\MainController::home
    requirements:
        _locale: '%app_locales%'
    defaults:
        _format: 'html'
        _locale: '%locale%'

homepage_without_trailing:
    path: /{_locale}{_<(?!/)>}
    controller: App\Controller\MainController::home
    requirements:
        _locale: '%app_locales%'
    defaults:
        _format: 'html'
        _locale: '%locale%'

homepage_raw:
    path: ""
    controller: App\Controller\MainController::home
    defaults:
        _format: 'html'
        _locale: '%locale%'

errors_404:
    path: 404.html
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: errors/404.html.twig
    options:
        stenope:
            sitemap: false

controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /{_locale<%app.supported_locales%>}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
