name: CI - Quality Gates

on: [push]

jobs:
  build-and-test:
    name: 'Build and test'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-versions: [ '8.1' ]

    steps:
      # Setup Github actions
      # https://github.com/actions/checkout (official)
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: mbstring xml ctype iconv intl pdo pdo_mysql dom filter gd iconv json mbstring pdo

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: ${{ matrix.php-versions }}
          path: src/
          standard: phpcs.xml.dist
